{{- range $name, $cfg := .Values.components }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
  labels:
    app: {{ $name }}
    {{- include "example-voting-app.labels" $ | nindent 4 }}
spec:
  replicas: {{ $cfg.replicas | default 1 }}
  selector:
    matchLabels:
      app: {{ $name }}
      {{- include "example-voting-app.labels" $ | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{ $name }}
        {{- include "example-voting-app.labels" $ | nindent 8 }}
    spec:
      containers:
        - name: {{ $cfg.type | default $name }}
          image: "{{ $cfg.image }}"
          {{- if $cfg.containerPort }}
          ports:
            - containerPort: {{ $cfg.containerPort }}
              name: {{ $cfg.type | default $name }}
          {{- end }}
          {{- if $cfg.env }}
          env:
            {{- range $cfg.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          {{- end }}
          {{- if $cfg.volumeMounts }}
          volumeMounts:
            {{- range $cfg.volumeMounts }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
            - name: vote-app-pv
              mountPath: /shared-data-vol
            - name: test-backend-override-config
              mountPath: /shared-data-vol/override-setting.txt
              subPath: override-setting.txt
            {{- end }}
          {{- end }}
      {{- if $cfg.volumes }}
      volumes:
        {{- range $cfg.volumes }}
        - name: {{ .name }}
          {{- if hasKey . "emptyDir" }}
          emptyDir: {}
          {{- end }}
        {{- end }}
        - name: vote-app-pv
          persistentVolumeClaim:
            claimName: vote-app-pvc
        - name: test-backend-override-config
          configMap:
            name: test-override-setting-config
      {{- end }}
---
{{- end }}