apiVersion: v1
kind: PersistentVolume
metadata:
  name: vote-app-pv
spec:
  capacity:
    storage: 512Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain

  hostPath:
    path: /home/ubuntu/data
    type: Directory
