{{- range $name, $cfg := .Values.components }}
{{- if $cfg.containerPort }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  labels:
    app: {{ $name }}
    {{- include "example-voting-app.labels" $ | nindent 4 }}
spec:
  type: {{ $cfg.serviceType | default "ClusterIP" }}
  selector:
    app: {{ $name }}
    {{- include "example-voting-app.labels" $ | nindent 4 }}
  ports:
    - name: {{ printf "%s-service" $name }}
      port: {{ $cfg.servicePort }}
      targetPort: {{ $cfg.containerPort }}
      {{- if and (eq $cfg.serviceType "NodePort") ($cfg.nodePort) }}
      nodePort: {{ $cfg.nodePort }}
      {{- end }}
---
{{- end }}
{{- end }}
