#!/usr/bin/env bash
set -euo pipefail

# Minimal job summary writer.
# Only requires two env vars to be provided by the caller:
# - TRIGGER_COMMENT : the triggering comment text (or empty)
# - COMMENT_ID      : id of the triggering comment (optional)

TRIGGER_COMMENT=${TRIGGER_COMMENT:-}
COMMENT_ID=${COMMENT_ID:-}

# Try to infer PR number from env or the event payload (if available)
if [ -n "${PR_NUMBER:-}" ]; then
  PR_NUMBER=${PR_NUMBER}
elif [ -n "${GITHUB_EVENT_PATH:-}" ] && [ -f "${GITHUB_EVENT_PATH}" ]; then
  PR_NUMBER=$(python - <<PY 2>/dev/null
import json,os
try:
    ev=json.load(open(os.environ['GITHUB_EVENT_PATH']))
    print(ev.get('issue',{}).get('number',''))
except Exception:
    print('')
PY
)
else
  PR_NUMBER=""
fi

# Where to write the summary
if [ -n "${GITHUB_STEP_SUMMARY:-}" ]; then
  SUMMARY_FILE=${GITHUB_STEP_SUMMARY}
else
  SUMMARY_FILE=/tmp/ai_job_summary.md
fi

echo "## 🤖 AI PR Review" > "$SUMMARY_FILE" || true
if [ -n "$PR_NUMBER" ]; then
  echo "- PR: [#${PR_NUMBER}](${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/pull/${PR_NUMBER})" >> "$SUMMARY_FILE" || true
fi

if [ -n "$COMMENT_ID" ]; then
  echo "- Trigger: [link to comment](${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/issues/${PR_NUMBER}#issuecomment-${COMMENT_ID})" >> "$SUMMARY_FILE" || true
else
  echo "- Trigger comment: \"${TRIGGER_COMMENT}\"" >> "$SUMMARY_FILE" || true
fi

echo "" >> "$SUMMARY_FILE" || true
echo "(Generated by ai-pr-review)" >> "$SUMMARY_FILE" || true

exit 0
