---
- name: Install Helm
  shell: |
    curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
  args:
    executable: /bin/bash

- name: Run RKE2 installer for server
  shell: |
    curl -sfL https://get.rke2.io | sudo sh -

- name: Enable and start RKE2 server service
  systemd:
    name: "rke2-server.service"
    enabled: yes
    state: started

- name: "Gather system service facts"
  ansible.builtin.service_facts:

- name: "Display RKE2 Server operational status"
  ansible.builtin.debug:
    msg: "RKE2 Server is currently {{ ansible_facts.services['rke2-server.service'].state }}"

- name: "Copy kubectl binary to system bin directory"
  # Use remote_src: yes to copy the file directly on the target server
  ansible.builtin.copy:
    src: /var/lib/rancher/rke2/bin/kubectl
    dest: /usr/local/bin/kubectl
    mode: '0755'
    remote_src: yes

- name: "Create .kube directory in home of user: {{ ansible_user }}"
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/.kube"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0700'

- name: "Copy rke2.yaml to {{ ansible_user }} kubeconfig"
  ansible.builtin.copy:
    src: /etc/rancher/rke2/rke2.yaml
    dest: "/home/{{ ansible_user }}/.kube/config"
    remote_src: yes
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0600' # Security: only the owner can read this config

- name: "Add KUBECONFIG environment variable to {{ ansible_user }} .bashrc"
  ansible.builtin.lineinfile:
    path: "/home/{{ ansible_user }}/.bashrc"
    line: 'export KUBECONFIG=~/.kube/config'
    state: present

- name: Copy RBAC file
  copy:
    src: "../../../../github-runner-setting/runner-rbac.yml"
    dest: "/tmp/rbac-runner.yaml"
    mode: '0644'

- name: Write values files for GitHub runners
  copy:
    content: |
      githubConfigUrl: "{{ item.github_repo }}"
      githubConfigSecret:
        github_token: "{{ github_pat }}"
      containerMode:
        type: "dind"
      template:
        spec:
          serviceAccountName: "{{ item.serviceAccountName }}"
          containers:
            - name: runner
              image: "{{ item.custom_image }}"
              command: ["/home/runner/run.sh"]
              securityContext:
                readOnlyRootFilesystem: false
    dest: "/tmp/{{ item.runner_name }}-values.yaml"
    mode: '0644'
  loop: "{{ github_runner_configs }}"