---
# Helm Installation
- name: Check if Helm is installed
  stat:
    path: /usr/local/bin/helm
  register: helm_check

- name: Install Helm
  when: not helm_check.stat.exists
  block:
    - name: Download Helm installer
      get_url:
        url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        dest: /tmp/get_helm.sh
        mode: '0755'

    - name: Run Helm installer
      shell: /tmp/get_helm.sh
      args:
        executable: /bin/bash

# RKE2 Installation and Configuration
- name: Ensure RKE2 config directory exists
  file:
    path: /etc/rancher/rke2
    state: directory
    mode: '0755'

- name: Check RKE2 binary
  stat:
    path: /usr/local/bin/rke2
  register: rke2_bin

- name: Download and Run RKE2 Installer
  shell: curl -sfL https://get.rke2.io | sh -
  environment:
    INSTALL_RKE2_VERSION: "{{ rke2_version }}"
  when: not rke2_bin.stat.exists

- name: Start RKE2 service
  systemd:
    name: rke2-server
    state: started
    enabled: yes

- name: "Gather system service facts"
  service_facts:

- name: "Display RKE2 Server operational status"
  debug:
    msg: "RKE2 Server ({{ rke2_version }}) is currently {{ ansible_facts.services['rke2-server.service'].state }}"

- name: "Copy kubectl binary to system bin directory"
  # Use remote_src: yes to copy the file directly on the target server
  copy:
    src: /var/lib/rancher/rke2/bin/kubectl
    dest: /usr/local/bin/kubectl
    mode: '0755'
    remote_src: yes

- name: "Create .kube directory in home of user: {{ ansible_user }}"
  file:
    path: "/home/{{ ansible_user }}/.kube"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0700'

- name: "Copy rke2.yaml to {{ ansible_user }} kubeconfig"
  copy:
    src: /etc/rancher/rke2/rke2.yaml
    dest: "/home/{{ ansible_user }}/.kube/config"
    remote_src: yes
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0600' # Security: only the owner can read this config

- name: "Add KUBECONFIG environment variable to {{ ansible_user }} .bashrc"
  lineinfile:
    path: "/home/{{ ansible_user }}/.bashrc"
    line: 'export KUBECONFIG=~/.kube/config'
    state: present

- name: "Add kubectl alias to {{ ansible_user }} .bashrc"
  lineinfile:
    path: "/home/{{ ansible_user }}/.bashrc"
    line: 'alias k=kubectl'
    state: present

- name: Read node-token from Master
  slurp:
    src: /var/lib/rancher/rke2/server/node-token
  register: master_token_encoded

- name: Set token fact for other plays
  set_fact:
    rke2_token: "{{ master_token_encoded.content | b64decode | trim }}"