---
- name: Install Keepalived and HAProxy
  apt:
    name:
      - keepalived
      - haproxy
    state: present
    update_cache: yes

- name: Copy Keepalived configuration
  template:
    src: "{{ role_path }}/conf/keepalived.conf.j2"
    dest: /etc/keepalived/keepalived.conf
  notify: Restart Keepalived

- name: Append K8s configuration to HAProxy
  blockinfile:
    path: /etc/haproxy/haproxy.cfg
    marker: "# {mark} ANSIBLE MANAGED BLOCK FOR K8S #"
    block: |
      # --- Cấu hình cho App 1 ---
      frontend app1_frontend
          bind *:80
          bind *:443
          mode tcp
          default_backend app1_backend

      backend app1_backend
          mode tcp
          server worker1 192.168.5.133
          server worker2 192.168.5.134
  notify: Restart HAProxy
