---
- name: Install Keepalived and HAProxy
  apt:
    name:
      - keepalived
      - haproxy
    state: present
    update_cache: yes

- name: Copy Keepalived configuration
  template:
    src: "{{ role_path }}/conf/keepalived.conf.j2"
    dest: /etc/keepalived/keepalived.conf
    mode: '0644'
    validate: 'keepalived --config-test --use-file=%s'
  notify: Restart Keepalived

- name: Configure Kubernetes ingress frontends and backends in HAProxy
  blockinfile:
    path: /etc/haproxy/haproxy.cfg
    marker: "# {mark} ANSIBLE MANAGED BLOCK FOR K8S #"
    validate: 'haproxy -c -f %s'
    block: |
      frontend k8s_ingress_http
          bind *:{{ ingress_http_port }}
          mode tcp
          default_backend k8s_ingress_http

      backend k8s_ingress_http
          mode tcp
      {% for host in groups['workers'] %}
          server {{ host }} {{ hostvars[host]['ansible_host'] }}:{{ ingress_http_port }} check
      {% endfor %}

      frontend k8s_ingress_https
          bind *:{{ ingress_https_port }}
          mode tcp
          default_backend k8s_ingress_https

      backend k8s_ingress_https
          mode tcp
      {% for host in groups['workers'] %}
          server {{ host }} {{ hostvars[host]['ansible_host'] }}:{{ ingress_https_port }} check
      {% endfor %}
  notify: Restart HAProxy
