ansible_user: ubuntu
ssh_key_dir: "/home/{{ ansible_user }}/.ssh"
local_key_dir: "{{ playbook_dir }}/../ssh_keys"
master_hostname: "devops-master"
master_ip: "192.168.56.20"
rke2_server_ip: "192.168.56.11"
