# Kubernetes Cluster Configuration
rke2_version: "v1.28.10+rke2r1"
rke2_kubeconfig: "/home/{{ ansible_user }}/.kube/config"

# Github Runner Configuration
github_pat: "ghp_xxx"

github_runner_configs:
  - runner_name: "stg-ci-runner-set"
    custom_image: "tantran0411/github-runner-ci:v1"
    github_repo: "https://github.com/devops-framework"
    serviceAccountName: "staging-runner-sa"
