# Kubernetes Cluster Configuration
rke2_version: "v1.28.10+rke2r1"
rke2_kubeconfig: "/home/{{ ansible_user }}/.kube/config"

# Github Runner Configurationv
github_runner_configs:
  - runner_name: "stg-ci-runner-set"
    custom_image: "tantran0411/github-runner-ci:v1"
    github_repo: "https://github.com/devops-framework"
    serviceAccountName: "staging-runner-sa"

# ArgoCD Configuration
argocd_projects:
  - project_name: "staging"
    description: "Test only"
    source_repos:
      - "*"
    destinations:
      - server: "*"
        name: "*"
        namespace: "*"
    
argocd_repos:
  - name: "e-commerce-frontstore"
    github_repo: "https://github.com/devops-framework/e-commerce-jsf-storefront.git"
    project: "staging"
    connection_method: "VIA HTTP/HTTPS"
  - name: "e-commerce-order-service"
    github_repo: "https://github.com/devops-framework/e-commerce-order-service.git"
    project: "staging"
    connection_method: "VIA HTTP/HTTPS"
  - name: "e-commerce-product-service"
    github_repo: "https://github.com/devops-framework/e-commerce-product-service.git"
    project: "staging"
    connection_method: "VIA HTTP/HTTPS"

argocd_apps:
  - app_name: "e-commerce-order-service"
    project_name: "staging"
    sync_policy: "Manual"
    repo_url: "https://github.com/devops-framework/e-commerce-order-service.git"
    revision_branches: "master" # Nếu chọn branches thì để trống revision_tags
    revision_tags: "" # Nếu chọn tags thì để trống revision_branches
    path: "devops/cd/k8s/overlays/staging"
    destination_cluster: "https://kubernetes.default.svc"
    destination_namespace: "backend-stg"
    # directory_recurse: true
  - app_name: "e-commerce-jsf-storefront"
    project_name: "staging"
    sync_policy: "Manual"
    repo_url: "https://github.com/devops-framework/e-commerce-jsf-storefront.git"
    revision_branches: "master" # Nếu chọn branches thì để trống revision_tags
    revision_tags: "" # Nếu chọn tags thì để trống revision_branches
    path: "devops/cd/k8s/overlays/staging"
    destination_cluster: "https://kubernetes.default.svc"
    destination_namespace: "frontend-stg"
    # directory_recurse: true
  - app_name: "e-commerce-product-service"
    project_name: "staging"
    sync_policy: "Manual"
    repo_url: "https://github.com/devops-framework/e-commerce-product-service.git"
    revision_branches: "master" # Nếu chọn branches thì để trống revision_tags
    revision_tags: "" # Nếu chọn tags thì để trống revision_branches
    path: "devops/cd/k8s/overlays/staging"
    destination_cluster: "https://kubernetes.default.svc"
    destination_namespace: "backend-stg"
    # directory_recurse: true