apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/storefront

namespace: frontend-stg

images:
  - name: tantran0411/e-commerce-jsf
    newTag: "gha-staging-REPLACE_ME"
