apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-config
  namespace: backend-stg
data:
  config.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <configuration>
        <entry>
            <key>PRODUCT_SERVICE_HOST</key>
            <value>product-service</value>
            
            <key>PRODUCT_SERVICE_PORT</key>
            <value>8080</value>
        </entry>
    </configuration>
