apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: backend-stg
  labels:
    app: order-service
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      serviceAccountName: order-service
      automountServiceAccountToken: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: order-service
          image: tantran0411/e-commerce-order-service:gha-staging-master-3a277c0
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
              readOnly: true
          env:
            - name: CONFIG_FILE_PATH
              value: "/app/config/config.xml"
          livenessProbe:
            httpGet:
              path: /api/healthcheck
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /api/healthcheck
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: config-volume
          configMap:
            name: order-service-config
            items:
              - key: config.xml
                path: config.xml
