---
- name: Add HashiCorp repo
  shell: |
    curl -fsSL https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
    echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/hashicorp.list
    apt update
  args:
    executable: /bin/bash

- name: Install Terraform and Packer
  apt:
    name:
      - terraform
      - packer
    state: present

- name: Install Ansible
  apt:
    name: ansible
    state: present
