---
- hosts: all
  become: yes
  roles:
    - role: common
    - role: users
  tasks:
    - name: Include roles listed in host variable selected_roles (if any)
      include_role:
        name: "{{ item }}"
      loop: "{{ selected_roles | default([]) }}"
      when: selected_roles is defined
      tags: always
