---
- name: Setup RKE2 Master
  hosts: master
  become: yes
  roles:
    - rke2-server

- name: Setup RKE2 Agents
  hosts: workers
  become: yes
  vars:
    rke2_token: "{{ hostvars[groups['master'][0]]['rke2_token'] }}"
  roles:
    - rke2-agent

- name: Setup VIP Load Balancer
  hosts: loadbalancer
  become: yes
  roles:
    - vip_lb

- name: Deploy Github Runner to RKE2 Cluster
  hosts: master
  become: yes
  roles:
    - github-rac

- name: Deploy ArgoCD to RKE2 Cluster
  hosts: master
  become: yes
  roles:
    - argocd