---
- name: Get join command from master node
  shell: |
    ssh -i /home/{{ ansible_user }}/.ssh/id_rsa \
        -o StrictHostKeyChecking=no \
        {{ ansible_user }}@{{ master_ip }} \
        "sudo kubeadm token create --print-join-command --ttl 1h"
  register: join_cmd_raw

- name: Show join command (debug)
  debug:
    msg: "{{ join_cmd_raw.stdout }}"

- name: Join the cluster
  become: yes
  shell: "{{ join_cmd_raw.stdout }}"
  args:
    executable: /bin/bash
  when: join_cmd_raw.stdout is defined and join_cmd_raw.stdout != ''
