apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: backend-stg
  labels:
    app: product-service
    target_env: stg
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      serviceAccountName: product-service
      automountServiceAccountToken: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: product-service
          image: tantran0411/e-commerce-product-service:gha-staging-master-2449dd2
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          ports:
            - containerPort: 8080
          startupProbe:
            tcpSocket:
              port: 8080
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8080
            periodSeconds: 15
          readinessProbe:
            tcpSocket:
              port: 8080
            periodSeconds: 10
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
