name: Reusable Build and Push
on:
  workflow_call:
    inputs:
      app_name:
        required: true
        description: App name impacts to docker image tag
        type: string
      dockerfile_path:
        required: true
        description: Dockerfile path
        type: string
      gha_environment:
        required: true
        description: Environment to get Github secrets and variables
        type: string
      
    secrets:
      DISCORD_WEBHOOK_URL:
        required: true
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true

jobs:
  build:
    name: Build & Push
    runs-on: stg-ci-runner-set
    environment: ${{ inputs.gha_environment }}
    steps:
      - name: Discord start notification
        uses: devops-framework/iac-vagrant-k8s-cluster-local/.github/actions/discord-notifier@dev
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          status: 'start'
          title: '🚀 Start build ${{ inputs.app_name }}'
          message: |
            **Environment**: ${{ inputs.gha_environment }}
            **Action:** On-push

            **App Name:** ${{ inputs.app_name }}
            **Actor:** ${{ github.actor }}
            **Branch:** `${{ github.ref_name }}`

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set short SHA
        id: get-short-sha
        run: echo "short_sha=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Set image tag
        id: get-image-tag
        run: echo "image_tag=gha-staging-${{ steps.get-short-sha.outputs.short_sha }}" >> $GITHUB_OUTPUT

      - name: Run Docker Build & Push
        id: docker-build-push
        uses: devops-framework/iac-vagrant-k8s-cluster-local/.github/actions/dockerhub-build-push@dev
        with:
          docker_username: ${{ secrets.DOCKER_USERNAME }}
          docker_password: ${{ secrets.DOCKER_PASSWORD }}
          image_name: ${{ inputs.app_name }}
          image_tag: ${{ steps.get-image-tag.outputs.image_tag }}
          dockerfile_path: "./devops/ci/docker/staging/Dockerfile"

      - name: Update Image Tag in Deployment
        id: updated_image_tag
        shell: bash
        run: |
          IMAGE_TAG="${{ steps.get-image-tag.outputs.image_tag }}"
          MANIFEST_PATH="devops/cd/k8s/staging/kustomization.yaml"
          
          sed -i "s|newTag: .*|newTag: $IMAGE_TAG|g" $MANIFEST_PATH
          echo "manifest_path=${MANIFEST_PATH}" >> $GITHUB_OUTPUT

      - name: Commit and Push changes
        id: auto-commit-step
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(staging): Auto pin image to ${{ steps.get-short-sha.outputs.short_sha }}"
          file_pattern: '${{ steps.updated_image_tag.outputs.manifest_path }}'
          branch: ${{ github.ref_name }}
          repository: .

      - name: Discord result notification
        if: always()
        uses: devops-framework/iac-vagrant-k8s-cluster-local/.github/actions/discord-notifier@dev
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          status: ${{ job.status }}
          title: '📂 Build results'
          message: |
            **Environment**: ${{ inputs.gha_environment }}
            **Status:** ${{ job.status }}
            **Action:** On-push
            
            **App Name:** ${{ inputs.app_name }}
            **Actor:** ${{ github.actor }}
            **Branch:** `${{ github.ref_name }}`
            **Image Tag:** [${{ steps.get-image-tag.outputs.image_tag || 'None' }}](${{ steps.docker-build-push.outputs.dockerhub_url || 'None' }})
            **Manifest Change:** ${{ steps.auto-commit-step.outputs.changes_detected == 'true' && format('[{1}](https://github.com/{0}/commit/{1})', github.repository, steps.auto-commit-step.outputs.commit_hash) || 'No changes' }}
