name: Reusable Build and Push
on:
  workflow_call:
    inputs:
      app_name:
        required: true
        description: App name impacts to docker image tag
        type: string
      dockerfile_path:
        required: true
        description: Dockerfile path
        type: string
      gha_environment:
        required: true
        description: Environment to get Github secrets and variables
        type: string
      
    secrets:
      DISCORD_WEBHOOK_URL:
        required: true
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true

jobs:
  build:
    name: Build & Push
    runs-on: stg-ci-runner-set
    environment: ${{ inputs.gha_environment }}
    steps:
      - name: Discord start notification
        uses: devops-framework/iac-vagrant-k8s-cluster-local/.github/actions/discord-notifier@dev
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          status: 'start'
          title: '🚀 Start build ${{ inputs.app_name }}'
          message: |
            **Environment**: ${{ inputs.gha_environment }}
            **Action:** On-push

            **App Name:** ${{ inputs.app_name }}
            **Actor:** ${{ github.actor }}
            **Branch:** `${{ github.ref_name }}`

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GIHUB_PAT }}
          fetch-depth: 0

      - name: Set IMAGE_TAG
        id: get-image-tag
        run: |
          echo "short_sha=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
          echo "image_tag=gha-staging-${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Run Docker Build & Push
        id: docker-build-push
        uses: devops-framework/iac-vagrant-k8s-cluster-local/.github/actions/dockerhub-build-push@dev
        with:
          docker_username: ${{ secrets.DOCKER_USERNAME }}
          docker_password: ${{ secrets.DOCKER_PASSWORD }}
          image_name: ${{ inputs.app_name }}
          image_tag: ${{ steps.get-image-tag.outputs.image_tag }}
          dockerfile_path: ${{ inputs.dockerfile_path }}

      - name: Discord result notification
        if: always()
        uses: devops-framework/iac-vagrant-k8s-cluster-local/.github/actions/discord-notifier@dev
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          status: ${{ job.status }}
          title: 'Build has been completed'
          message: |
            **Environment**: ${{ inputs.gha_environment }}
            **Status:** ${{ job.status }}
            **Action:** Manual

            **App Name:** ${{ inputs.app_name }}
            **Actor:** ${{ github.actor }}
            **Branch:** `${{ github.ref_name }}`
            **Image Tag:** [${{ steps.get-image-tag.outputs.image_tag || 'None' }}](${{ steps.docker-build-push.outputs.dockerhub_url }})
